version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mi-app-php-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - DB_URL=${DB_URL}
      - DB_APIKEY=${DB_APIKEY}
